### ISSUE TITLE
issue in documentation

### ISSUE THREAD

**Issue by ajay143444** [couchbase/docs-sdk-python#57]
https://docs.couchbase.com/python-sdk/2.5/failure-considerations.html#timeouts

in the above link, there is a mistake in below sentence in timeouts section.
The length of time a client **waits for an a response** from the server is configurable (see your language’s Couchbase SDK reference for how to configure it).

its should be **waits for a response** in the sentence.

**Comment by RichardSmedley** [comment]
Thanks. Now fixed (will be in production docs by tomorrow).
